### PR TITLE
Updated zpp_bits to v2.0

### PR DESCRIPTION
**Pull request by eyalz800**

### CODE REVIEW

**Comment by eyalz800** [comment]
Let's see if this one performs any better

**Comment by eyalz800** [comment]
@felixguendling are the results any different?

**Comment by felixguendling** [comment]
Sorry, at the moment I'm on holiday and I don't have a PC to make any experiments on. I'll run it next week when I'm back.

**Comment by eyalz800** [comment]
Sure thanks for the help

**Pull request merged**
